name: API Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH  
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Debug Environment
        run: |
          pwd
          ls -R
          python -c "import sys; print(sys.path)"

        - name: Test Import
          run: python -c "from utils.api_client import APIClient; print('Import successful!')"

      
      - name: Run API Tests
        run: pytest --html=reports/test_report.html --self-contained-html
